# build.yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          # 이 옵션을 true로 설정하면, fromJson 생성 시 $checkedCreate, $checkedConvert 등의
          # 헬퍼 함수를 사용하여 더 엄격한 검사를 수행하고,
          # JSON 필드 누락이나 타입 불일치 시 CheckedFromJsonException을 발생시킵니다.
          checked: true
          # 필요에 따라 다른 json_serializable 옵션도 여기에 추가할 수 있습니다.
          # 예:
          # explicit_to_json: true
          # field_rename: kebab # JSON 필드명 스타일 (kebab-case, snake_case, pascal_case 등)
